#!/usr/bin/env python3
# AsteriskLint -- an Asterisk PBX config syntax checker
# Copyright (C) 2015-2016  Walter Doekes, OSSO B.V.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
import os
import sys

# Add ../ to the path, useful when running from development dir.
if os.path.basename(os.path.dirname(os.path.abspath(__file__))) == 'scripts':
    sys.path.insert(
        0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# Remove bindir from path, lest we try to import from self.
try:
    sys.path.remove(os.path.dirname(os.path.abspath(__file__)))
except ValueError:
    pass

from asterisklint.main import main

if __name__ == '__main__':
    sys.exit(main(sys.argv[1:], os.environ))
